# docker-compose.yml
version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:5173'  # Adjust ports as needed
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '8000:8000'
