version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  # Django Backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static_files:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=django-insecure-production-key-change-this
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"

  # Vue.js Frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000/api

volumes:
  postgres_data:
  static_files:
